Repository ThomasKramp/Smart-Backpack, pull requests merged in 2021-04, with the labels that each got.

#34 Pre-set Item List Added
  SmartBackpack/app/src/main/java/com/example/smartbackpack/List/ItemActivity.java
  SmartBackpack/app/src/main/res/drawable/Pants.jpg
  SmartBackpack/app/src/main/res/drawable/Underwear.jpg
  SmartBackpack/app/src/main/res/drawable/Water.jpg
  SmartBackpack/app/src/main/res/layout/activity_item.xml
  SmartBackpack/app/src/main/res/layout/list_item_layout.xml
  SmartBackpack/app/src/main/res/values/strings.xml
Labels: ItemList

#35 Continues Bluetooth Communication
  SmartBackpack/app/src/main/java/com/example/smartbackpack/Bluetooth/BluetoothFragment.java
  SmartBackpack/app/src/main/java/com/example/smartbackpack/MainActivity.java
Labels: Bluetooth, Task

#38 Update to the layout
  SmartBackpack/app/src/main/res/drawable/pants.jpg
  SmartBackpack/app/src/main/res/drawable/rounded_button.xml
  SmartBackpack/app/src/main/res/drawable/underwear.jpg
  SmartBackpack/app/src/main/res/drawable/water.jpg
  SmartBackpack/app/src/main/res/layout/activity_item.xml
  SmartBackpack/app/src/main/res/layout/activity_main.xml
  SmartBackpack/app/src/main/res/layout/device_item_layout.xml
  SmartBackpack/app/src/main/res/layout/fragment_bluetooth.xml
  SmartBackpack/app/src/main/res/layout/fragment_home.xml
  SmartBackpack/app/src/main/res/layout/fragment_list.xml
  SmartBackpack/app/src/main/res/layout/fragment_moisture.xml
  SmartBackpack/app/src/main/res/layout/fragment_weight.xml
  SmartBackpack/app/src/main/res/layout/list_item_layout.xml
  SmartBackpack/app/src/main/res/values/colors.xml
  SmartBackpack/app/src/main/res/values/strings.xml
  SmartBackpack/app/src/main/res/values/styles.xml
Labels: UI

#41 Created Notifications
  SmartBackpack/app/src/main/java/com/example/smartbackpack/Bluetooth/BluetoothFragment.java
  SmartBackpack/app/src/main/java/com/example/smartbackpack/MainActivity.java
  SmartBackpack/app/src/main/res/layout/fragment_bluetooth.xml
Labels: Notifications

#45 BugFix bluetooth:
  SmartBackpack/app/src/main/java/com/example/smartbackpack/Fragments/BluetoothFragment.java
  SmartBackpack/app/src/main/java/com/example/smartbackpack/MainActivity.java
Labels: bug

#44 Bug fix disappearance of list items when changing tabs
  SmartBackpack/app/src/main/java/com/example/smartbackpack/Fragments/ListFragment.java
  SmartBackpack/app/src/main/java/com/example/smartbackpack/MainActivity.java
Labels: bug
